### ISSUE TITLE
[JS] [Regression] Model googleai/gemini-1.5-pro-latest not found

### ISSUE THREAD

**Issue by odbol** [firebase/genkit#1311]
**Describe the bug**
Set up a .prompt file like this:

```
---
model: googleai/gemini-1.5-pro-latest
config:
  temperature: 0.85
  candidateCount: 4
input:
...
```

This used to work before the 0.9 update, but now it's broken. 

I tried using the stable version `model: googleai/gemini-1.5-pro`, but it performs poorly (doesn't return JSON according to my schema). The latest version is much better at respecting the schema. 

Please bring back the ability to use the latest versions!

**To Reproduce**
1. Run the prompt
2. Error `Model googleai/gemini-1.5-pro-latest not found`

**Expected behavior**
Prompt should complete successfully

**Screenshots**

**Runtime (please complete the following information):**
 - OS: MacOS
 - Version 0.9

** Node version
 -  run `node --version` at paste here
 node --version
v18.20.5

**Additional context**
