### ISSUE TITLE
[JS] Structured Output is not followed for Dotprompt

### ISSUE THREAD

**Issue by i2amsam** [firebase/genkit#1438]
[[Hoisting from Discord thread]](https://discord.com/channels/1255578482214305893/1255583176089276566/threads/1310749690316324955)

myprompt.prompt
``` 
--
model: googleai/gemini-1.5-flash
config:
  temperature: 1
  topK: 32
  topP: 0.95
tools: []
input:
  schema:
    title: string
    description: string
    url: string
output:
  schema: ComposeArticleOutputSchema
---
Imagine a {{title}} doing {{description}}
```

index.ts
```
import { genkit, z } from 'genkit';
import { googleAI } from '@genkit-ai/googleai';
const ai = genkit({
    plugins: [ googleAI() ],
});

export const ComposeArticleOutputSchema = ai.defineSchema(
    'ComposeArticleOutputSchema', z.object({
      response: z.string(),
    }));

export const composeArticleFlow = ai.defineFlow(
    {
        name: "composeArticleFlow",
        inputSchema: z.object({ title: z.string(), description: z.string(), urls: z.array(z.string()) }),
        outputSchema: ComposeArticleOutputSchema,
    },
    async ({ title, description, urls }) => {
        const generateRoomPrompt = await ai.prompt<z.ZodTypeAny, typeof ComposeArticleOutputSchema>("myprompt");
        const response = await generateRoomPrompt(
            { title, description, url: 'foobar' },
            { model: 'googleai/gemini-1.5-flash', 
                output: { schema: ComposeArticleOutputSchema, format: 'json'  } }
        );
        const output = response.output;
        if (!output) {
            throw new Error("Failed to generate data");
        }
        return output;
    }
);

(async () => {
    console.log(((await composeArticleFlow({
        title: 'Anne of Green Gables',
        description: 'The famous book',
        urls: []
    }))));
})();
```

Tested with `0.9.6`
```
node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

Error: Failed to generate data
    at Flow.flowFn (/home/user/mytestapp/index.ts:28:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
