### ISSUE TITLE
[JS]  Dev UI ignores temperature “0” in dotprompt file and defaults to “0.4”

### ISSUE THREAD

**Issue by kenryu42** [firebase/genkit#2899]
**Describe the bug**
When setting the model temperature to `0` or `0.0` in the dotprompt file, the Dev UI does not reflect this value and continues to show `0.4 `instead.

**To Reproduce**

```js
// index.js
import { genkit } from 'genkit';
import { googleAI } from '@genkit-ai/googleai';

const ai = genkit({ plugins: [googleAI({
    apiKey: process.env.GEMINI_API_KEY
})] });

const helloPrompt = ai.prompt('hello');
```

```yaml
# hello.prompt
---
model: googleai/gemini-2.0-flash
config:
  temperature: 0.0
  topK: 32
  topP: 0.95
---

{{role "system"}}
You are a helpful assistant.

{{role "user"}}
What is the meaning of life? Explain in a few words.
```

`genkit start -- node --watch src/index.js`

**Expected behavior**
The Dev UI should read and display the exact temperature value from the dotprompt file. When set to `0` (or `0.0`), the UI should show `0` (or `0.0`) rather than defaulting to `0.4`.

**Screenshots**
<img width="1798" alt="Image" src="https://github.com/user-attachments/assets/9ee03144-4a58-43db-b443-acbc3048c355" />

**Runtime:**
 - OS: macOS Sequoia `15.5`
 - Node Version: `22.14.0 `
 - Genkit Version: `1.8.0`
