### ISSUE TITLE
[Go] failed to convert parts: unsupported prompt format: *dotprompt.MediaPart

### ISSUE THREAD

**Issue by webfrank** [firebase/genkit#2976]
**Describe the bug**
Created a .prompt file with placeholder for image {{media url=imageUrl}}, set the input for imageUrl to inline data:.... and execute the prompt.

**To Reproduce**
```go
image, err := os.ReadFile(path)
if err != nil {
	log.Print(err)
	return nil, err
}

log.Printf("Analyzing image %s\n", path)

prompt := genkit.LookupPrompt(g, "shelf")

resp, err := prompt.Execute(ctx, ai.WithInput(map[string]any{"imageUrl": "data:image/jpeg;base64," + base64.StdEncoding.EncodeToString(image)}))

if err != nil {
	log.Printf("could not generate model response: %v", err)
	return nil, err
}

log.Print(resp.Text())
```

dotprompt file:

```yaml
---
model: googleai/gemini-2.5-flash-preview-04-17
config:
  temperature: 0.1
input:
  schema:
    imageUrl: string
output:
  products: integer
  missing: integer
---
Analyze the provided image of a store shelf. Take in account only the foremost one.

{{media url=imageUrl}}
```

**Expected behavior**
Execution of prompt, same as genkit.Generate()

**Runtime (please complete the following information):**
 - OS: MacOS
 - Version 0.5.4

** Go version
 -  go version go1.24.3 darwin/amd64
